[2025-07-07T03:13:42.075+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dim_marketing_program.run_etl_dim_marketing_program manual__2025-07-07T03:13:39.734208+00:00 [queued]>
[2025-07-07T03:13:42.092+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dim_marketing_program.run_etl_dim_marketing_program manual__2025-07-07T03:13:39.734208+00:00 [queued]>
[2025-07-07T03:13:42.095+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T03:13:42.143+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_etl_dim_marketing_program> on 2025-07-07 03:13:39.734208+00:00
[2025-07-07T03:13:42.157+0000] {standard_task_runner.py:57} INFO - Started process 341 to run task
[2025-07-07T03:13:42.185+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dim_marketing_program', 'run_etl_dim_marketing_program', 'manual__2025-07-07T03:13:39.734208+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/etl_dim_marketing_program.py', '--cfg-path', '/tmp/tmpc7capqs3']
[2025-07-07T03:13:42.194+0000] {standard_task_runner.py:85} INFO - Job 128: Subtask run_etl_dim_marketing_program
[2025-07-07T03:13:42.329+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_dim_marketing_program.run_etl_dim_marketing_program manual__2025-07-07T03:13:39.734208+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T03:13:42.432+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dim_marketing_program' AIRFLOW_CTX_TASK_ID='run_etl_dim_marketing_program' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T03:13:39.734208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T03:13:39.734208+00:00'
[2025-07-07T03:13:42.450+0000] {base.py:73} INFO - Using connection ID '***_insurance_bi' for task execution.
[2025-07-07T03:13:42.466+0000] {warnings.py:110} WARNING - /opt/airflow/dags/etl_dim_marketing_program.py:64: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  df['program_status'] = pd.np.select(conditions, choices, default='Unknown')

[2025-07-07T03:13:42.477+0000] {base.py:73} INFO - Using connection ID '***_insurance_dw' for task execution.
[2025-07-07T03:13:42.502+0000] {python.py:183} INFO - Done. Returned value was: Loaded 10 marketing program records with batch ID: MKTG_LOAD_20250707_031342
[2025-07-07T03:13:42.526+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_dim_marketing_program, task_id=run_etl_dim_marketing_program, execution_date=20250707T031339, start_date=20250707T031342, end_date=20250707T031342
[2025-07-07T03:13:42.564+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T03:13:42.590+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
