[2025-07-07T06:16:59.382+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_etl.trigger_export_dashboard manual__2025-07-07T06:13:47.259414+00:00 [queued]>
[2025-07-07T06:16:59.395+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_etl.trigger_export_dashboard manual__2025-07-07T06:13:47.259414+00:00 [queued]>
[2025-07-07T06:16:59.395+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T06:16:59.404+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_export_dashboard> on 2025-07-07 06:13:47.259414+00:00
[2025-07-07T06:16:59.407+0000] {standard_task_runner.py:57} INFO - Started process 469 to run task
[2025-07-07T06:16:59.409+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'master_etl', 'trigger_export_dashboard', 'manual__2025-07-07T06:13:47.259414+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/master_etl.py', '--cfg-path', '/tmp/tmp_c7cwqf6']
[2025-07-07T06:16:59.409+0000] {standard_task_runner.py:85} INFO - Job 178: Subtask trigger_export_dashboard
[2025-07-07T06:16:59.460+0000] {task_command.py:410} INFO - Running <TaskInstance: master_etl.trigger_export_dashboard manual__2025-07-07T06:13:47.259414+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T06:16:59.531+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='master_etl' AIRFLOW_CTX_TASK_ID='trigger_export_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:13:47.259414+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:13:47.259414+00:00'
[2025-07-07T06:16:59.631+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T06:16:59.630+0000] {trigger_dagrun.py:201} INFO - Waiting for export_dashboard_data on 2025-07-07T06:16:59.531880+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T06:17:59.683+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T06:17:59.681+0000] {trigger_dagrun.py:201} INFO - Waiting for export_dashboard_data on 2025-07-07T06:16:59.531880+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T06:18:59.756+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T06:18:59.754+0000] {trigger_dagrun.py:201} INFO - Waiting for export_dashboard_data on 2025-07-07T06:16:59.531880+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T06:19:59.843+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T06:19:59.840+0000] {trigger_dagrun.py:201} INFO - Waiting for export_dashboard_data on 2025-07-07T06:16:59.531880+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T06:20:59.933+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T06:20:59.931+0000] {trigger_dagrun.py:201} INFO - Waiting for export_dashboard_data on 2025-07-07T06:16:59.531880+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T06:22:00.052+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T06:22:00.046+0000] {trigger_dagrun.py:201} INFO - Waiting for export_dashboard_data on 2025-07-07T06:16:59.531880+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T06:23:00.155+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/trigger_dagrun.py", line 208, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: export_dashboard_data failed with failed states failed
[2025-07-07T06:23:00.162+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=master_etl, task_id=trigger_export_dashboard, execution_date=20250707T061347, start_date=20250707T061659, end_date=20250707T062300
[2025-07-07T06:23:00.181+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 178 for task trigger_export_dashboard (export_dashboard_data failed with failed states failed; 469)
[2025-07-07T06:23:00.232+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-07T06:23:00.261+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
